remove dependency on lsb init-functions

diff --git a/server/aesdsocket-start-stop b/server/aesdsocket-start-stop
--- a/server/aesdsocket-start-stop
+++ b/server/aesdsocket-start-stop
@@ -14,22 +14,18 @@ DESC="aesdsocket server"
 # exit if daemon is not executable
 test -x $DAEMON || exit 0
 
-# source helper functions
-. /lib/lsb/init-functions
-
 start_it_up()
 {
-  log_daemon_msg "Starting $DESC" "$NAME"
+  echo "Starting $DESC"
   start-stop-daemon --start --verbose --name $NAME --exec $DAEMON -- -d
-  log_end_msg $?
+  [ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 shut_it_down()
 {
-  log_daemon_msg "Stopping $DESC" "$NAME"
+  echo "Stopping $DESC"
   start-stop-daemon --stop --verbose --oknodo --name $NAME
-  log_end_msg $?
-  rm -f $PIDFILE
+  [ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
@@ -39,19 +35,8 @@ case "$1" in
   stop)
     shut_it_down
   ;;
-  reload|force-reload)
-    shut_it_down
-    start_it_up
-  ;;
-  restart)
-    shut_it_down
-    start_it_up
-  ;;
-  status)
-    status_of_proc $DAEMON $NAME && exit 0 || exit $?
-    ;;
   *)
-    echo "Usage: /etc/init.d/$NAME {start|stop|reload|restart|force-reload|status}" >&2
+    echo "Usage: /etc/init.d/$NAME {start|stop}" >&2
     exit 2
   ;;
 esac
